-- Enable PostGIS for Radar features
CREATE EXTENSION IF NOT EXISTS postgis;
-- ── PROFILES ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  xparq_name TEXT NOT NULL,
  bio TEXT,
  photo_url TEXT,
  cover_photo_url TEXT,
  birth_date_encrypted TEXT NOT NULL,
  age_group TEXT NOT NULL,
  blue_orbit BOOLEAN DEFAULT FALSE,
  is_adult_verified BOOLEAN DEFAULT FALSE,
  nsfw_opt_in BOOLEAN DEFAULT FALSE,
  mbti TEXT,
  enneagram TEXT,
  zodiac TEXT,
  blood_type TEXT,
  constellations TEXT [],
  -- Array of strings
  is_online BOOLEAN DEFAULT TRUE,
  ghost_mode BOOLEAN DEFAULT FALSE,
  account_status TEXT DEFAULT 'active',
  deletion_requested_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  -- Location for Radar
  location_lat DOUBLE PRECISION,
  location_lng DOUBLE PRECISION,
  location_updated_at TIMESTAMPTZ,
  last_location GEOGRAPHY(POINT, 4326),
  -- Design Preferences
  cover_photo_y_percent DOUBLE PRECISION DEFAULT 0.5,
  -- Counters (mapped from Firestore metrics)
  total_pulse_count INTEGER DEFAULT 0,
  nsfw_pulse_count INTEGER DEFAULT 0,
  -- New Profile Fields (v2)
  handle TEXT UNIQUE,
  handle_updated_at TIMESTAMPTZ,
  gender TEXT,
  location_name TEXT,
  occupation TEXT,
  links TEXT [],
  extended_bio TEXT,
  last_seen TIMESTAMPTZ,
  photo_y_percent DOUBLE PRECISION DEFAULT 0.5,
  photo_alignment TEXT DEFAULT 'center',
  is_expanded_header BOOLEAN DEFAULT FALSE,
  work TEXT,
  education TEXT,
  experience TEXT,
  skills TEXT [],
  is_contact_public BOOLEAN DEFAULT FALSE,
  fcm_token TEXT,
  backup_cid TEXT,
  backup_at TIMESTAMPTZ,
  primary_device_id TEXT
);
-- ── PULSES ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.pulses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  uid UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  author_name TEXT NOT NULL,
  author_avatar TEXT,
  author_planet_type TEXT,
  author_is_high_risk BOOLEAN DEFAULT FALSE,
  content TEXT NOT NULL,
  image_url TEXT,
  is_nsfw BOOLEAN DEFAULT FALSE,
  pulse_type TEXT DEFAULT 'post' CHECK (pulse_type IN ('post', 'story')),
  spark_count INTEGER DEFAULT 0,
  echo_count INTEGER DEFAULT 0,
  warp_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  edited_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_pulses_pulse_type ON public.pulses (pulse_type, created_at);
-- ── PULSE INTERACTIONS (SPARKS/LIKES/WARPS) ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.pulse_interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pulse_id UUID REFERENCES public.pulses(id) ON DELETE CASCADE NOT NULL,
  uid UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('spark', 'warp')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(pulse_id, uid, type)
);
-- ── ECHOES (COMMENTS) ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.echoes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  pulse_id UUID REFERENCES public.pulses(id) ON DELETE CASCADE NOT NULL,
  uid UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  author_name TEXT NOT NULL,
  author_avatar TEXT,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
-- ── ORBITS (FOLLOWS) ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.orbits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  followed_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(follower_id, followed_id)
);
-- ── ARCHIVED ACCOUNTS ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.archived_accounts (
  identifier TEXT PRIMARY KEY,
  permanently_deleted_at TIMESTAMPTZ DEFAULT NOW()
);
-- ── CHATS ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.chats (
  id TEXT PRIMARY KEY,
  participants UUID [] NOT NULL,
  last_message TEXT,
  last_sender UUID REFERENCES public.profiles(id),
  last_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  is_sensitive BOOLEAN DEFAULT FALSE,
  is_spam BOOLEAN DEFAULT FALSE,
  accepted_at TIMESTAMPTZ,
  is_group BOOLEAN DEFAULT FALSE,
  name TEXT,
  group_avatar TEXT,
  vanishing_duration INTEGER
);
-- ── MESSAGES ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id TEXT REFERENCES public.chats(id) ON DELETE CASCADE NOT NULL,
  sender_id UUID REFERENCES public.profiles(id) NOT NULL,
  content_encrypted TEXT NOT NULL,
  is_sensitive BOOLEAN DEFAULT FALSE,
  is_spam BOOLEAN DEFAULT FALSE,
  is_offline_relay BOOLEAN DEFAULT FALSE,
  delivered BOOLEAN DEFAULT FALSE,
  read BOOLEAN DEFAULT FALSE,
  message_type TEXT DEFAULT 'text',
  metadata JSONB DEFAULT '{}'::JSONB,
  expires_at TIMESTAMPTZ,
  deleted_uids UUID [] DEFAULT '{}'::UUID [],
  timestamp TIMESTAMPTZ DEFAULT NOW()
);
-- ── CHAT SETTINGS ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.chat_settings (
  uid UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  chat_id TEXT NOT NULL REFERENCES public.chats(id) ON DELETE CASCADE,
  is_pinned BOOLEAN DEFAULT FALSE,
  is_archived BOOLEAN DEFAULT FALSE,
  silenced_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (uid, chat_id)
);
-- ── STATUS DELAYS (Anti-Stalking) ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.status_delays (
  minor_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (minor_id, sender_id)
);
-- ── CONTACT REQUESTS ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.contact_requests (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  requester_uid UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  target_uid UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  responded_at TIMESTAMPTZ,
  UNIQUE(requester_uid, target_uid)
);
-- ── RLS POLICIES ────────────────────────────────────────────────────────
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pulses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pulse_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.echoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orbits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.status_delays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;
-- Profiles: Publicly readable, owner can update
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR
SELECT USING (TRUE);
CREATE POLICY "Users can update own profile" ON public.profiles FOR
UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR
INSERT WITH CHECK (auth.uid() = id);
-- Chats: Participants can see/create
CREATE POLICY "Users can see own chats" ON public.chats FOR
SELECT USING (auth.uid() = ANY(participants));
CREATE POLICY "Users can create chats" ON public.chats FOR
INSERT WITH CHECK (auth.uid() = ANY(participants));
CREATE POLICY "Users can update their chats" ON public.chats FOR
UPDATE USING (auth.uid() = ANY(participants));
-- Messages: Participants can see/insert
CREATE POLICY "Users can see own messages" ON public.messages FOR
SELECT USING (
    EXISTS (
      SELECT 1
      FROM public.chats
      WHERE id = messages.chat_id
        AND auth.uid() = ANY(participants)
    )
  );
CREATE POLICY "Users can send messages to their chats" ON public.messages FOR
INSERT WITH CHECK (
    sender_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.chats
      WHERE id = messages.chat_id
        AND auth.uid() = ANY(participants)
    )
  );
CREATE POLICY "Users can update messages in their chats" ON public.messages FOR
UPDATE USING (
    EXISTS (
      SELECT 1
      FROM public.chats
      WHERE id = messages.chat_id
        AND auth.uid() = ANY(participants)
    )
  );
-- Chat Settings: Owner only
CREATE POLICY "Users can manage their own chat settings" ON public.chat_settings FOR ALL USING (auth.uid() = uid);
-- Orbits: Owner only
CREATE POLICY "Users can manage their own orbits" ON public.orbits FOR ALL USING (auth.uid() = follower_id);
CREATE POLICY "Anyone can view orbits" ON public.orbits FOR
SELECT USING (TRUE);
-- ── RPC FUNCTIONS ───────────────────────────────────────────────────────
-- send_chat_message (legacy and v2 updates mentioned but consolidating here)
CREATE OR REPLACE FUNCTION send_chat_message(
    p_chat_id TEXT,
    p_sender_id UUID,
    p_content TEXT,
    p_is_sensitive BOOLEAN,
    p_is_offline_relay BOOLEAN,
    p_is_spam BOOLEAN,
    p_plaintext_preview TEXT
  ) RETURNS VOID AS $$ BEGIN
INSERT INTO public.messages (
    chat_id,
    sender_id,
    content_encrypted,
    is_sensitive,
    is_offline_relay,
    is_spam
  )
VALUES (
    p_chat_id,
    p_sender_id,
    p_content,
    p_is_sensitive,
    p_is_offline_relay,
    p_is_spam
  );
UPDATE public.chats
SET last_message = p_plaintext_preview,
  last_sender = p_sender_id,
  last_at = NOW(),
  is_sensitive = p_is_sensitive,
  is_spam = p_is_spam
WHERE id = p_chat_id;
END;
$$ LANGUAGE plpgsql;
-- toggle_chat_pin
CREATE OR REPLACE FUNCTION toggle_chat_pin(p_chat_id TEXT, p_is_pinned BOOLEAN) RETURNS VOID AS $$ BEGIN
INSERT INTO public.chat_settings (uid, chat_id, is_pinned)
VALUES (auth.uid(), p_chat_id, p_is_pinned) ON CONFLICT (uid, chat_id) DO
UPDATE
SET is_pinned = p_is_pinned,
  updated_at = NOW();
END;
$$ LANGUAGE plpgsql;
-- toggle_chat_archive
CREATE OR REPLACE FUNCTION toggle_chat_archive(p_chat_id TEXT, p_is_archived BOOLEAN) RETURNS VOID AS $$ BEGIN
INSERT INTO public.chat_settings (uid, chat_id, is_archived)
VALUES (auth.uid(), p_chat_id, p_is_archived) ON CONFLICT (uid, chat_id) DO
UPDATE
SET is_archived = p_is_archived,
  updated_at = NOW();
END;
$$ LANGUAGE plpgsql;
-- silence_chat
CREATE OR REPLACE FUNCTION silence_chat(p_chat_id TEXT, p_until TIMESTAMPTZ) RETURNS VOID AS $$ BEGIN
INSERT INTO public.chat_settings (uid, chat_id, silenced_until)
VALUES (auth.uid(), p_chat_id, p_until) ON CONFLICT (uid, chat_id) DO
UPDATE
SET silenced_until = p_until,
  updated_at = NOW();
END;
$$ LANGUAGE plpgsql;
-- delete_message_for_me
CREATE OR REPLACE FUNCTION delete_message_for_me(p_message_id BIGINT) RETURNS VOID AS $$ BEGIN
UPDATE public.messages
SET deleted_uids = array_append(deleted_uids, auth.uid())
WHERE id = p_message_id
  AND NOT (auth.uid() = ANY(deleted_uids));
END;
$$ LANGUAGE plpgsql;
-- get_unread_counts
CREATE OR REPLACE FUNCTION get_unread_counts(p_uid UUID) RETURNS TABLE (chat_id TEXT, unread_count BIGINT) AS $$ BEGIN RETURN QUERY
SELECT m.chat_id,
  COUNT(*) as unread_count
FROM public.messages m
  JOIN public.chats c ON m.chat_id = c.id
WHERE p_uid = ANY(c.participants)
  AND m.sender_id != p_uid
  AND m.read = false
GROUP BY m.chat_id;
END;
$$ LANGUAGE plpgsql;
-- ── TRIGGERS ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_last_location() RETURNS TRIGGER AS $$ BEGIN IF NEW.location_lat IS NOT NULL
  AND NEW.location_lng IS NOT NULL THEN NEW.last_location = ST_SetSRID(
    ST_MakePoint(NEW.location_lng, NEW.location_lat),
    4326
  )::geography;
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER tr_update_last_location BEFORE
INSERT
  OR
UPDATE OF location_lat,
  location_lng ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_last_location();



