// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxbXmKPnAT4Gz2w8n_U0zsxbtLA86A6ec',
    appId: '1:625282680034:web:654a9b23f63505d358cabb',
    messagingSenderId: '625282680034',
    projectId: 'xparq-b59e4',
    authDomain: 'xparq-b59e4.firebaseapp.com',
    storageBucket: 'xparq-b59e4.firebasestorage.app',
    measurementId: 'G-SBDF92SZZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOzAYVUxLMOyjLW-BV4t0q11o0-cOCXqo',
    appId: '1:625282680034:android:2dee766445a0829e58cabb',
    messagingSenderId: '625282680034',
    projectId: 'xparq-b59e4',
    storageBucket: 'xparq-b59e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhMDyqBGeBcSB91iUfeNNC_1NO79iJSOk',
    appId: '1:625282680034:ios:6ff3e5867ca57fa558cabb',
    messagingSenderId: '625282680034',
    projectId: 'xparq-b59e4',
    storageBucket: 'xparq-b59e4.firebasestorage.app',
    iosBundleId: 'com.example.xparqMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhMDyqBGeBcSB91iUfeNNC_1NO79iJSOk',
    appId: '1:625282680034:ios:6ff3e5867ca57fa558cabb',
    messagingSenderId: '625282680034',
    projectId: 'xparq-b59e4',
    storageBucket: 'xparq-b59e4.firebasestorage.app',
    iosBundleId: 'com.example.xparqMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxbXmKPnAT4Gz2w8n_U0zsxbtLA86A6ec',
    appId: '1:625282680034:web:30708202bbeec38758cabb',
    messagingSenderId: '625282680034',
    projectId: 'xparq-b59e4',
    authDomain: 'xparq-b59e4.firebaseapp.com',
    storageBucket: 'xparq-b59e4.firebasestorage.app',
    measurementId: 'G-ZZHDK3BZTX',
  );
}
